/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CropUnit Specifies the unit in which a crop box is expressed.
type CropUnit string

// List of CropUnit
const (
	PIXEL CropUnit = "Pixel"
	PERCENT CropUnit = "Percent"
)
