/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// StickyNoteAnnotationIcon Defines the different available icons for a sticky note annotation.
type StickyNoteAnnotationIcon string

// List of StickyNoteAnnotationIcon
const (
	COMMENT StickyNoteAnnotationIcon = "Comment"
	KEY StickyNoteAnnotationIcon = "Key"
	NOTE StickyNoteAnnotationIcon = "Note"
	HELP StickyNoteAnnotationIcon = "Help"
	NEW_PARAGRAPH StickyNoteAnnotationIcon = "NewParagraph"
	PARAGRAPH StickyNoteAnnotationIcon = "Paragraph"
	INSERT StickyNoteAnnotationIcon = "Insert"
	CHECK StickyNoteAnnotationIcon = "Check"
	CIRCLE StickyNoteAnnotationIcon = "Circle"
	CROSS StickyNoteAnnotationIcon = "Cross"
	CROSS_HAIRS StickyNoteAnnotationIcon = "CrossHairs"
	RIGHT_ARROW StickyNoteAnnotationIcon = "RightArrow"
	RIGHT_POINTER StickyNoteAnnotationIcon = "RightPointer"
	STAR StickyNoteAnnotationIcon = "Star"
	UP_ARROW StickyNoteAnnotationIcon = "UpArrow"
	UP_LEFT_ARROW StickyNoteAnnotationIcon = "UpLeftArrow"
)
