/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// IntegerResponse Represents an integer response.
type IntegerResponse struct {
	Error Error `json:"Error,omitempty"`
	// The response value.
	Value int32 `json:"Value,omitempty"`
}
