/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfSetInitialViewParameters Represents the parameters for a set initial view action.
type PdfSetInitialViewParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	PageMode PdfInitViewPageMode `json:"PageMode,omitempty"`
	LayoutMode PdfInitViewLayoutMode `json:"LayoutMode,omitempty"`
	NonFullScreenPageMode PdfInitViewNonFullScreenPageMode `json:"NonFullScreenPageMode,omitempty"`
	// Specifies which page should be displayed when the document is opened.
	OpenPage int32 `json:"OpenPage,omitempty"`
	// Specifies the default zoom factor to be used when the document is opened. Value of 1 to represent the 100% zoom, 2 means 200%, 0,5 means 50%, etc.
	OpenZoom float32 `json:"OpenZoom,omitempty"`
	// A flag specifying whether to hide the viewer application’s tool bars when the document is active. Default value: false.
	HideToolbar bool `json:"HideToolbar,omitempty"`
	// (Optional) A flag specifying whether to hide the viewer application’s menu bar when the document is active. Default value: false.
	HideMenubar bool `json:"HideMenubar,omitempty"`
	// (Optional) A flag specifying whether to hide user interface elements in the document’s window (such as scroll bars and navigation controls),  leaving only the document’s contents displayed. Default value: false.
	HideWindowUI bool `json:"HideWindowUI,omitempty"`
	// (Optional) A flag specifying whether to resize the document’s window to fit the size of the first displayed page. Default value: false.
	FitWindow bool `json:"FitWindow,omitempty"`
	// (Optional) A flag specifying whether to position the document’s window in the center of the screen. Default value: false.
	CenterWindow bool `json:"CenterWindow,omitempty"`
	// (Optional; PDF 1.4) A flag specifying whether the window’s title bar should display the document title taken from the Title entry of the document information dictionary.  If false, the title bar should instead display the name of the PDF file containing the document. Default value: false.
	DisplayDocTitle bool `json:"DisplayDocTitle,omitempty"`
}
