/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PageText Holds the extracted text from a given page of a document.
type PageText struct {
	// Specifies the number of the page.
	PageNumber int32 `json:"PageNumber,omitempty"`
	// The text extraction result.
	ExtractedText *string `json:"ExtractedText,omitempty"`
}
