/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LongResponse Represents a long response.
type LongResponse struct {
	Error Error `json:"Error,omitempty"`
	// The response value.
	Value int64 `json:"Value,omitempty"`
}
