/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ClonedImageRegion Represents a cloned image region.
type ClonedImageRegion struct {
	ImageRegion ImageRegion `json:"ImageRegion,omitempty"`
	// The file identifier of the image.
	FileId *string `json:"FileId,omitempty"`
}
