/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfMergeParameters Represents the parameters for a merge action.
type PdfMergeParameters struct {
	// Specifies the identifiers of the documents to be merged.
	FilesId []string `json:"FilesId"`
	// Specifies if file attachments should be included in merged document.
	IncludeAttachments bool `json:"IncludeAttachments,omitempty"`
}
