/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfSaveAsJpegParameters Represents the parameters for a save as JPEG acion.
type PdfSaveAsJpegParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to be saved as JPEG.
	PageRange *string `json:"PageRange,omitempty"`
	// Specifies the level of quality to be used for the JPEG compression, from 1 (poorest) to 100 (greatest).
	Quality int32 `json:"Quality,omitempty"`
	// Specifies if the encoded JPEG image must be progressive.
	Progressive bool `json:"Progressive,omitempty"`
	// Specifies the resolution to be used for the rendition process.
	Resolution float32 `json:"Resolution,omitempty"`
	// Specifies whether the form fields of the PDF shall be rendered.
	RenderFormFields bool `json:"RenderFormFields,omitempty"`
	// Specifies if the initial image resolution must be kept in case of raster-pdf processing.
	KeepRasterPDFResolution bool `json:"KeepRasterPDFResolution,omitempty"`
}
