/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ReduceWarningInfo Represents information about a warning that occured during a reduce action.
type ReduceWarningInfo struct {
	WarningCode ReduceWarningCode `json:"WarningCode,omitempty"`
	// The number of the page processed when the warning occured.
	PageNumber int32 `json:"PageNumber,omitempty"`
	// The number of the image of the page processed when the warning occured.
	PageImageNumber int32 `json:"PageImageNumber,omitempty"`
	// The warning message associated with the warning, if any.
	ExtWarningMessage *string `json:"ExtWarningMessage,omitempty"`
}
