/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfVersion Specifies a PDF version for a reduced document.
type PdfVersion string

// List of PdfVersion
const (
	PDF_VERSION_RETAIN_EXISTING PdfVersion = "PdfVersionRetainExisting"
	PDF_VERSION14 PdfVersion = "PdfVersion14"
	PDF_VERSION15 PdfVersion = "PdfVersion15"
	PDF_VERSION16 PdfVersion = "PdfVersion16"
	PDF_VERSION17 PdfVersion = "PdfVersion17"
	PDF_VERSION_A1A PdfVersion = "PdfVersionA1a"
	PDF_VERSION_A1B PdfVersion = "PdfVersionA1b"
	PDF_VERSION_A2A PdfVersion = "PdfVersionA2a"
	PDF_VERSION_A2B PdfVersion = "PdfVersionA2b"
)
