/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfLinearizeParameters Represents the parameters for a linearize action.
type PdfLinearizeParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies whether the document shall be packed, in order to reduce its size.
	PackDocument bool `json:"PackDocument,omitempty"`
}
