/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfAutoDeskewParameters Represents the parameters for an auto deskew action.
type PdfAutoDeskewParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the page or the page range to be auto-deskewed.
	PageRange string `json:"PageRange"`
	// Specifies the maximum skew angle to be detected. A value of below 15 is suggested.
	MaxAngleOfResearch float32 `json:"MaxAngleOfResearch,omitempty"`
	// Specifies whether the skew detection engine must be optimistic when detecting angles.  If you know the image is skewed, you should set this to true.
	Optimistic bool `json:"Optimistic,omitempty"`
}
