/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DocuViewareCertificate struct for DocuViewareCertificate
type DocuViewareCertificate struct {
	DisplayName *string `json:"DisplayName,omitempty"`
	Data *string `json:"Data,omitempty"`
	Password *string `json:"Password,omitempty"`
	TimestampServerURI *string `json:"TimestampServerURI,omitempty"`
	TimestampServerUserName *string `json:"TimestampServerUserName,omitempty"`
	TimestampServerUserPassword *string `json:"TimestampServerUserPassword,omitempty"`
}
