/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfDetectPageOrientationResponse Represents the response to a detect page orientation action request.
type PdfDetectPageOrientationResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Holds information about the detected page orientations.
	PageOrientations *[]PageOrientationInfo `json:"PageOrientations,omitempty"`
}
