/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfAConformance Specifies the different available PDF/A conformance levels.
type PdfAConformance string

// List of PdfAConformance
const (
	PDFA1A PdfAConformance = "PDFA1a"
	PDFA1B PdfAConformance = "PDFA1b"
	PDFA2A PdfAConformance = "PDFA2a"
	PDFA2B PdfAConformance = "PDFA2b"
	PDFA2U PdfAConformance = "PDFA2u"
	PDFA3A PdfAConformance = "PDFA3a"
	PDFA3B PdfAConformance = "PDFA3b"
	PDFA3U PdfAConformance = "PDFA3u"
)
