/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LoadDocumentFromByteArrayParameters Represents the parameters for an image loading request.
type LoadDocumentFromByteArrayParameters struct {
	// Specifies the data of the document.
	Content string `json:"Content"`
	// Specifies the name of the document.
	FileName *string `json:"FileName,omitempty"`
	ContentEncoding ContentEncoding `json:"ContentEncoding,omitempty"`
	// Specifies whether the response must contain a thumbnail of the first page of the document.
	GetPreview bool `json:"GetPreview,omitempty"`
	// Specifies, in pixels, the width of the thumbnail to be retrieved. Only applicable if GetPreview has been set to true.
	ThumbnailWidth int32 `json:"ThumbnailWidth,omitempty"`
	// Specifies, in pixels, the height of the thumbnail to be retrieved.  Only applicable if GetPreview has been set to true.
	ThumbnailHeight int32 `json:"ThumbnailHeight,omitempty"`
	// Specifies the background color of the thumbnail, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").   Only applicable if GetPreview has been set to true.
	ThumbnailBackgroundColor *string `json:"ThumbnailBackgroundColor,omitempty"`
	// Specifies if the size of the produced thumbnail is automatically adjusted to don't have any margin.  Only applicable if GetPreview has been set to true.
	ThumbnailFitToPageSize bool `json:"ThumbnailFitToPageSize,omitempty"`
}
