/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LinkAnnotationParameters Represents information about the Link Annotation.
type LinkAnnotationParameters struct {
	AnnotationLayout DrawableContentLayoutParameters `json:"AnnotationLayout"`
	LinkType LinkAnnotationType `json:"LinkType,omitempty"`
	// Specifies the link annotation destination page if the Page type is specified.
	LinkPage int32 `json:"LinkPage,omitempty"`
	// Specifies the link annotation destination URI if the Web type is specified.
	LinkUri *string `json:"LinkUri,omitempty"`
	// Specifies if the annotation border shall be drawn.
	ShowBorder bool `json:"ShowBorder,omitempty"`
	// Specifies the color of the annotation, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").
	Color *string `json:"Color,omitempty"`
}
