/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LinkAnnotationClickBehaviour the model 'LinkAnnotationClickBehaviour'
type LinkAnnotationClickBehaviour string

// List of LinkAnnotationClickBehaviour
const (
	DEFAULT LinkAnnotationClickBehaviour = "Default"
	CLICK_NAVIGATION LinkAnnotationClickBehaviour = "ClickNavigation"
	DOUBLE_CLICK_NAVIGATION LinkAnnotationClickBehaviour = "DoubleClickNavigation"
)
