/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// StringResponse Represents a string response.
type StringResponse struct {
	Error Error `json:"Error,omitempty"`
	// The response value.
	Value *string `json:"Value,omitempty"`
}
