/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageResizeParameters Represents the parameters for an image resize action.
type ImageResizeParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to resize.
	PageRange string `json:"PageRange"`
	// Specifies the resize horizontal parameter.
	ResizeHorizontal float32 `json:"ResizeHorizontal"`
	// Specifies the resize vertical parameter.
	ResizeVertical float32 `json:"ResizeVertical"`
	ResizeMode ResizeMode `json:"ResizeMode,omitempty"`
	ResizeUnit ResizeUnit `json:"ResizeUnit,omitempty"`
}
