/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfLoadDocumentResponse Represents the response to a load document action request.
type PdfLoadDocumentResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Specifies the file identifier of the loaded document.
	FileId *string `json:"FileId,omitempty"`
	// Specifies the number of pages into the loaded document.
	PageCount int32 `json:"PageCount,omitempty"`
	Encryption EncryptionAlgorithm `json:"Encryption,omitempty"`
	// Specifies if a password will be subsequently required to open the document.  Password can be provided using the SetPassword action / method.
	PasswordIsRequired bool `json:"PasswordIsRequired,omitempty"`
	// Specifies the data of a thumbnail from the first page of the document, in PNG format. Only applicable if the GetPreview field of the request has been set to true.
	ThumbnailData *string `json:"ThumbnailData,omitempty"`
}
