/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetDocumentPreviewParameters Represents the parameters for a get document preview action.
type GetDocumentPreviewParameters struct {
	// Specifies the identifier of the file to be previewed.
	FileId string `json:"FileId"`
	// Specifies, in pixels, the width of the thumbnail to be retrieved.
	ThumbnailWidth int32 `json:"ThumbnailWidth,omitempty"`
	// Specifies, in pixels, the height of the thumbnail to be retrieved.
	ThumbnailHeight int32 `json:"ThumbnailHeight,omitempty"`
	// Specifies the background color of the thumbnail, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").
	ThumbnailBackgroundColor *string `json:"ThumbnailBackgroundColor,omitempty"`
	// Specifies if the size of the produced thumbnail is automatically adjusted to don't have any margin.
	ThumbnailFitToPageSize bool `json:"ThumbnailFitToPageSize,omitempty"`
}
