/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// StickyNoteAnnotationParameters Represents information about the Sticky Note Annotation.
type StickyNoteAnnotationParameters struct {
	AnnotationLayout DrawableContentLayoutParameters `json:"AnnotationLayout"`
	StickyNoteIcon StickyNoteAnnotationIcon `json:"StickyNoteIcon,omitempty"`
	// Specify the author of the annotation, if any.
	Author *string `json:"Author,omitempty"`
	// Specify the subject of the annotation, if any.
	Subject *string `json:"Subject,omitempty"`
	// Specify the content of the annotation, if any.
	Content *string `json:"Content,omitempty"`
	// Specifies if the popup of annotation shall be opened by default.
	OpenPopup bool `json:"OpenPopup,omitempty"`
	// Specifies the color of the annotation, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").
	Color *string `json:"Color,omitempty"`
}
