/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BarcodeInfo Represents information about a read barcode.
type BarcodeInfo struct {
	Type BarcodeType `json:"Type,omitempty"`
	Barcode1DSymbology Barcode1DSymbology `json:"Barcode1DSymbology,omitempty"`
	// Specifies the data contained within the barcode.
	Data *string `json:"Data,omitempty"`
	// Specifies the horizontal top-left position of the barcode, in pixels.
	X1 int32 `json:"X1,omitempty"`
	// Specifies the horizontal top-right position of the barcode, in pixels.
	X2 int32 `json:"X2,omitempty"`
	// Specifies the horizontal bottom-left position of the barcode, in pixels.
	X3 int32 `json:"X3,omitempty"`
	// Specifies the horizontal bottom-right position of the barcode, in pixels.
	X4 int32 `json:"X4,omitempty"`
	// Specifies the vertical top-left position of the barcode, in pixels.
	Y1 int32 `json:"Y1,omitempty"`
	// Specifies the vertical top-right position of the barcode, in pixels.
	Y2 int32 `json:"Y2,omitempty"`
	// Specifies the vertical bottom-left position of the barcode, in pixels.
	Y3 int32 `json:"Y3,omitempty"`
	// Specifies the vertical bottom-right position of the barcode, in pixels.
	Y4 int32 `json:"Y4,omitempty"`
	// Specifies the left coordinates of the bounding box of the barcode, in inches.
	BboxLeftInches float32 `json:"BboxLeftInches,omitempty"`
	// Specifies the top coordinates of the bounding box of the barcode, in inches.
	BboxTopInches float32 `json:"BboxTopInches,omitempty"`
	// Specifies the width of the bounding box of the barcode, in inches.
	BboxWidthInches float32 `json:"BboxWidthInches,omitempty"`
	// Specifies the height of the bounding box of the barcode, in inches.
	BboxHeightInches float32 `json:"BboxHeightInches,omitempty"`
	// Specifies the number of the page on which the barcode was read.
	PageNumber int32 `json:"PageNumber,omitempty"`
	// Specifies the width, in pixels, of the page where the barcode has been decoded.
	PagePixelWidth int32 `json:"PagePixelWidth,omitempty"`
	// Specifies the height, in pixels, of the page where the barcode has been decoded.
	PagePixelHeight int32 `json:"PagePixelHeight,omitempty"`
	// Specifies the horizontal resolution, in pixel per inches, of the page where the barcode has been decoded.
	PageHorizontalResolution float32 `json:"PageHorizontalResolution,omitempty"`
	// Specifies the vertical resolution, in pixel per inches, of the page where the barcode has been decoded.
	PageVerticalResolution float32 `json:"PageVerticalResolution,omitempty"`
}
