/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DocumentPosition the model 'DocumentPosition'
type DocumentPosition string

// List of DocumentPosition
const (
	MIDDLE_LEFT DocumentPosition = "MiddleLeft"
	MIDDLE_RIGHT DocumentPosition = "MiddleRight"
	MIDDLE_CENTER DocumentPosition = "MiddleCenter"
	TOP_LEFT DocumentPosition = "TopLeft"
	TOP_RIGHT DocumentPosition = "TopRight"
	TOP_CENTER DocumentPosition = "TopCenter"
	BOTTOM_LEFT DocumentPosition = "BottomLeft"
	BOTTOM_RIGHT DocumentPosition = "BottomRight"
	BOTTOM_CENTER DocumentPosition = "BottomCenter"
)
