/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LineAnnotationEndingStyle Specifies an line annotation's ending style.
type LineAnnotationEndingStyle string

// List of LineAnnotationEndingStyle
const (
	SQUARE LineAnnotationEndingStyle = "Square"
	CIRCLE LineAnnotationEndingStyle = "Circle"
	DIAMOND LineAnnotationEndingStyle = "Diamond"
	OPEN_ARROW LineAnnotationEndingStyle = "OpenArrow"
	CLOSED_ARROW LineAnnotationEndingStyle = "ClosedArrow"
	NONE LineAnnotationEndingStyle = "None"
	BUTT LineAnnotationEndingStyle = "Butt"
	REVERSED_OPEN_ARROW LineAnnotationEndingStyle = "ReversedOpenArrow"
	REVERSED_CLOSED_ARROW LineAnnotationEndingStyle = "ReversedClosedArrow"
	SLASH LineAnnotationEndingStyle = "Slash"
)
