/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfInitViewNonFullScreenPageMode Defines how the document shall be displayed when exiting full-screen mode.
type PdfInitViewNonFullScreenPageMode string

// List of PdfInitViewNonFullScreenPageMode
const (
	NONE PdfInitViewNonFullScreenPageMode = "None"
	OUTLINE PdfInitViewNonFullScreenPageMode = "Outline"
	THUMBNAILS PdfInitViewNonFullScreenPageMode = "Thumbnails"
	OC PdfInitViewNonFullScreenPageMode = "OC"
)
