/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ToolbarStyle Specifies the toolbar style.
type ToolbarStyle string

// List of ToolbarStyle
const (
	AUTO ToolbarStyle = "Auto"
	DESKTOP ToolbarStyle = "Desktop"
	MOBILE ToolbarStyle = "Mobile"
)
