/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageSaveAsPdfmrcParameters Represents the parameters for a save as PDF MRC action.
type ImageSaveAsPdfmrcParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to be saved as PDF MRC.
	PageRange *string `json:"PageRange,omitempty"`
	Conformance PdfConformance `json:"Conformance,omitempty"`
	ColorImageCompression PdfImageCompressionScheme `json:"ColorImageCompression,omitempty"`
	BitonalImageCompression PdfImageCompressionScheme `json:"BitonalImageCompression,omitempty"`
	// Specifies the quality to be used for the compression of the images from the PDF.  Must be in the range [0 (best compression - worst quality) - 100 (worst quality - best compression)].
	ImageQuality int32 `json:"ImageQuality,omitempty"`
	// Specifies the resolution for downscaling the background layer, if any.
	DownscaleResolution int32 `json:"DownscaleResolution,omitempty"`
	// Specifies whether the MRC engine should try to preserve smoothing between different layers.   Enabling this option should globally enhance the text quality but also reduce the compression rate.
	PreserveSmoothing bool `json:"PreserveSmoothing,omitempty"`
	// Specifies whether the PDF shall be optimized for online distribution.
	FastWebView bool `json:"FastWebView,omitempty"`
	// Specifies the threshold value for the JBIG2 encoder pattern matching and substitution between 0 and 1. Any number lower than 1 may lead to lossy compression.
	JBIG2PMSThreshold float32 `json:"JBIG2PMSThreshold,omitempty"`
}
