/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DocumentLoadResponse Represents the response to a document loading action request.
type DocumentLoadResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Specifies the file identifier of the loaded document.
	FileId *string `json:"FileId,omitempty"`
	DocumentFormat DocumentFormat `json:"DocumentFormat,omitempty"`
	// Specifies the number of pages into the loaded document.
	PageCount int32 `json:"PageCount,omitempty"`
	// Specifies the data of a thumbnail from the first page of the document, in PNG format. Only applicable if the GetPreview field of the request has been set to true.
	ThumbnailData *string `json:"ThumbnailData,omitempty"`
}
