/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageCleanupDocumentParameters Represents the parameters for a cleanup document action.
type ImageCleanupDocumentParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to cleanup.
	PageRange string `json:"PageRange"`
	// Specifies whether the dark borders of the document image shall be replaced with white content.
	RemoveBlackBorders bool `json:"RemoveBlackBorders,omitempty"`
	// Specifies whether the document shall be deskewed.
	Deskew bool `json:"Deskew,omitempty"`
	// Specifies whether punch holes shall be removed from the left margin of the document.
	RemoveLeftMarginPunchHoles bool `json:"RemoveLeftMarginPunchHoles,omitempty"`
	// Specifies whether punch holes shall be removed from the top margin of the document.
	RemoveTopMarginPunchHoles bool `json:"RemoveTopMarginPunchHoles,omitempty"`
	// Specifies whether punch holes shall be removed from the right margin of the document.
	RemoveRightMarginPunchHoles bool `json:"RemoveRightMarginPunchHoles,omitempty"`
	// Specifies whether punch holes shall be removed from the bottom margin of the document.
	RemoveBottomMarginPunchHoles bool `json:"RemoveBottomMarginPunchHoles,omitempty"`
	// Specifies the strength of the despeckle filter to be applied on the image.
	DespeckleStrength int32 `json:"DespeckleStrength,omitempty"`
}
