/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TextAlignment Defines the different available text alignments.
type TextAlignment string

// List of TextAlignment
const (
	NEAR TextAlignment = "Near"
	CENTER TextAlignment = "Center"
	FAR TextAlignment = "Far"
)
