/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfSaveDocumentResponse Represents the response to a save document action request.
type PdfSaveDocumentResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Specifies the data of the saved document.
	Data *string `json:"Data,omitempty"`
	// Specifies the name of the saved document.
	FileName *string `json:"FileName,omitempty"`
}
