/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfSaveAsTiffResponse Represents the response to a save as TIFF action request.
type PdfSaveAsTiffResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// The page(s) of the PDF saved as TIFF image(s).
	PageImages *[]PageImage `json:"PageImages,omitempty"`
}
