/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfGetPageThumbnailParameters Represents the parameters for a get page thumbnail action.
type PdfGetPageThumbnailParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the page or the range of pages to get a thumbnail from.
	PageRange string `json:"PageRange"`
	// Specifies the width, in points, of the thumbnail(s).
	ThumbnailWidth int32 `json:"ThumbnailWidth,omitempty"`
	// Specifies the height, in points, of the thumbnail(s).
	ThumbnailHeight int32 `json:"ThumbnailHeight,omitempty"`
	// Specifies the background color of the thumbnail(s), using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").
	BackgroundColor *string `json:"BackgroundColor,omitempty"`
	// Specifies if the size of the produced thumbnail is automatically adjusted to don't have any margin.
	ThumbnailFitToPageSize bool `json:"ThumbnailFitToPageSize,omitempty"`
}
