/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfSplitParameters Represents the parameters for a split action.
type PdfSplitParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	SplitMethod PdfSplitMethod `json:"SplitMethod"`
	// Specifies, respectively for the SplitByPageCount and SplitByFileSize split methods, the number of pages or the maximum size, in kilobytes, of the produced files.
	SplitValue int32 `json:"SplitValue"`
	// Specifies whether the file(s) created as a result of the action shall be available for immediate download.
	ImmediateDownload bool `json:"ImmediateDownload,omitempty"`
}
