/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfInsertNewPageParameters Represents the parameters for an insert new page action.
type PdfInsertNewPageParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page where the new page(s) shall be inserted.
	PageNumber int32 `json:"PageNumber"`
	// Specifies the number of pages that must be inserted.
	PageCount int32 `json:"PageCount,omitempty"`
	// Specifies, in points, the width of the page(s) to be inserted.
	Width float32 `json:"Width,omitempty"`
	// Specifies, in points, the height of the page(s) to be inserted.
	Height float32 `json:"Height,omitempty"`
}
