/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DocuViewareLocale User specific locale.
type DocuViewareLocale string

// List of DocuViewareLocale
const (
	AUTO DocuViewareLocale = "Auto"
	FR DocuViewareLocale = "Fr"
	EN DocuViewareLocale = "En"
	RO DocuViewareLocale = "Ro"
	AR DocuViewareLocale = "Ar"
	DE DocuViewareLocale = "De"
	IT DocuViewareLocale = "It"
	TR DocuViewareLocale = "Tr"
	SK DocuViewareLocale = "Sk"
	CS DocuViewareLocale = "Cs"
	ES DocuViewareLocale = "Es"
	DA DocuViewareLocale = "Da"
	RU DocuViewareLocale = "Ru"
	PT DocuViewareLocale = "Pt"
	NL DocuViewareLocale = "Nl"
	PL DocuViewareLocale = "Pl"
	HU DocuViewareLocale = "Hu"
	BG DocuViewareLocale = "Bg"
	EL DocuViewareLocale = "El"
	ZH DocuViewareLocale = "Zh"
	JA DocuViewareLocale = "Ja"
	SV DocuViewareLocale = "Sv"
	NO DocuViewareLocale = "No"
	KO DocuViewareLocale = "Ko"
	HE DocuViewareLocale = "He"
	FI DocuViewareLocale = "Fi"
	SL DocuViewareLocale = "Sl"
)
