/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageFilters Specifies a list of available image filters and effects.
type ImageFilters string

// List of ImageFilters
const (
	ADD_NOISE ImageFilters = "addNoise"
	AQUA ImageFilters = "aqua"
	BLUR ImageFilters = "blur"
	DIFFUSE ImageFilters = "diffuse"
	FIRE ImageFilters = "fire"
	GRAYSCALE ImageFilters = "grayscale"
	SEPIA ImageFilters = "sepia"
	NEGATIVE ImageFilters = "negative"
	PIXELIZE ImageFilters = "pixelize"
	RELIEF ImageFilters = "relief"
	SCAN_LINE ImageFilters = "scanLine"
	SHARPEN ImageFilters = "sharpen"
	SMOOTH ImageFilters = "smooth"
	EDGE_ENHANCEMENT ImageFilters = "edgeEnhancement"
	CONTOUR ImageFilters = "contour"
	EMBOSS ImageFilters = "emboss"
	ENGRAVE ImageFilters = "engrave"
	DILATE ImageFilters = "dilate"
	ERODE ImageFilters = "erode"
	CONNECTED_CONTOUR ImageFilters = "connectedContour"
	SOFTEN ImageFilters = "soften"
	COLORIZE ImageFilters = "colorize"
	GAUSSIAN ImageFilters = "gaussian"
	MAX ImageFilters = "max"
	MIN ImageFilters = "min"
	MEDIAN ImageFilters = "median"
	SUBTRACT_BACKGROUND ImageFilters = "subtractBackground"
	UNSHARPMASK ImageFilters = "unsharpmask"
)
