/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RotateMode Specifies the rotation mode.
type RotateMode string

// List of RotateMode
const (
	VIEW RotateMode = "View"
	CURRENT_PAGE RotateMode = "CurrentPage"
)
