/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfScalePageParameters Represents the parameters for a scale page action.
type PdfScalePageParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages which shall be scaled.
	PageRange string `json:"PageRange"`
	// Specifies the horizontal scale factor, by which the width of the page shall be multiplied.
	ScaleX float32 `json:"ScaleX"`
	// Specifies the horizontal scale factor, by which the height of the page shall be multiplied.
	ScaleY float32 `json:"ScaleY"`
}
