/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PageViewMode Defines how the pages are displayed on the screen.
type PageViewMode string

// List of PageViewMode
const (
	SINGLE_PAGE_VIEW PageViewMode = "SinglePageView"
	MULTIPLE_PAGES_VIEW PageViewMode = "MultiplePagesView"
)
