/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LinkAnnotationType Defines the supported types of Link Annotation.
type LinkAnnotationType string

// List of LinkAnnotationType
const (
	PAGE LinkAnnotationType = "Page"
	WEB LinkAnnotationType = "Web"
)
