/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfLoadDocumentFromByteArrayParameters Represents the parameters for a load document action request.
type PdfLoadDocumentFromByteArrayParameters struct {
	// Specifies the data of the document.
	Content string `json:"Content"`
	// Specifies the name of the document.
	FileName *string `json:"FileName,omitempty"`
	// Specifies the password of the document.
	Password *string `json:"Password,omitempty"`
	Conformance PdfConformance `json:"Conformance,omitempty"`
	ContentEncoding ContentEncoding `json:"ContentEncoding,omitempty"`
	// Specifies whether color detection must be used while importing a raster format to PDF.
	EnableColorDetection bool `json:"EnableColorDetection,omitempty"`
	// Specifies whether the response must contain a thumbnail of the first page of the document.
	GetPreview bool `json:"GetPreview,omitempty"`
	// Specifies, in pixels, the width of the thumbnail to be retrieved. Only applicable if GetPreview has been set to true.
	ThumbnailWidth int32 `json:"ThumbnailWidth,omitempty"`
	// Specifies, in pixels, the height of the thumbnail to be retrieved.  Only applicable if GetPreview has been set to true.
	ThumbnailHeight int32 `json:"ThumbnailHeight,omitempty"`
	// Specifies the background color of the thumbnail, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").   Only applicable if GetPreview has been set to true.
	ThumbnailBackgroundColor *string `json:"ThumbnailBackgroundColor,omitempty"`
	// Specifies if the size of the produced thumbnail is automatically adjusted to don't have any margin.  Only applicable if GetPreview has been set to true.
	ThumbnailFitToPageSize bool `json:"ThumbnailFitToPageSize,omitempty"`
	// Specifies the page width, in points, of produced documents from txt files.
	TxtPageWidth float32 `json:"TxtPageWidth,omitempty"`
	// Specifies the page height, in points, of produced documents from txt files.
	TxtPageHeight float32 `json:"TxtPageHeight,omitempty"`
	// Specifies the page margin left, in points, of produced documents from txt files.
	TxtPageMarginLeft float32 `json:"TxtPageMarginLeft,omitempty"`
	// Specifies the page margin top, in points, of produced documents from txt files.
	TxtPageMarginTop float32 `json:"TxtPageMarginTop,omitempty"`
	// Specifies the page margin right, in points, of produced documents from txt files.
	TxtPageMarginRight float32 `json:"TxtPageMarginRight,omitempty"`
	// Specifies the page margin bottom, in points, of produced documents from txt files.
	TxtPageMarginBottom float32 `json:"TxtPageMarginBottom,omitempty"`
	TxtHorizontalTextAlignment TextAlignment `json:"TxtHorizontalTextAlignment,omitempty"`
	// Specifies the text size, in points, to be used for producing documents from txt files.
	TxtFontSize float32 `json:"TxtFontSize,omitempty"`
	// Specifies the name of the font to be used for producing documents from txt files.
	TxtFontFamily *string `json:"TxtFontFamily,omitempty"`
	// Specifies whether the font to be used for producing documents from txt files must have a bold style.
	TxtFontBold bool `json:"TxtFontBold,omitempty"`
	// Specifies whether the font to be used for producing documents from txt files must have an italic style.
	TxtFontItalic bool `json:"TxtFontItalic,omitempty"`
}
