/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ReadBarcodesResponse Represents the response to a read barcode page action request.
type ReadBarcodesResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Specifies the information of the different barcodes which have been read.
	Barcodes *[]BarcodeInfo `json:"Barcodes,omitempty"`
}
