/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ResizeMode The algorithm to be used during resizing.
type ResizeMode string

// List of ResizeMode
const (
	AUTO ResizeMode = "Auto"
	NEAREST_NEIGHBOR ResizeMode = "NearestNeighbor"
	BOX ResizeMode = "Box"
	LANCZOS3 ResizeMode = "Lanczos3"
	BILINEAR ResizeMode = "Bilinear"
	BICUBIC ResizeMode = "Bicubic"
	BSPLINE ResizeMode = "Bspline"
	CATMULL_ROM_SPLINE ResizeMode = "CatmullRomSpline"
)
