/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfSetPageBoxParameters Represents the parameters for a SetPageBox action.
type PdfSetPageBoxParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of page whose page box shall be set.
	PageRange string `json:"PageRange"`
	// Specifies, in points, the newly defined left position of the specified page box.
	Left float32 `json:"Left"`
	// Specifies, in points, the newly defined top position of the specified page box.
	Top float32 `json:"Top"`
	// Specifies, in points, the newly defined right position of the specified page box.
	Right float32 `json:"Right"`
	// Specifies, in points, the newly defined bottom position of the specified page box.
	Bottom float32 `json:"Bottom"`
	PageBox PdfPageBox `json:"PageBox,omitempty"`
}
