/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfConvertToPdfaParameters Represents the parameters for a convert to PDF/A action.
type PdfConvertToPdfaParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	Conformance PdfAConformance `json:"Conformance,omitempty"`
	// If set to true, conversion engine will use the page vectorization in case direct conversion is not possible.
	AllowVectorization bool `json:"AllowVectorization,omitempty"`
	// If set to true, conversion engine will use the page rasterization in case direct conversion and verorization are not possible or allowed.
	AllowRasterization bool `json:"AllowRasterization,omitempty"`
}
