/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageGetPageThumbnailParameters Represents the parameters for a get page thumbnail action.
type ImageGetPageThumbnailParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the page or the range of pages to get a thumbnail from.
	PageRange string `json:"PageRange"`
	// Specifies the width, in points, of the thumbnail(s).
	ThumbnailWidth int32 `json:"ThumbnailWidth,omitempty"`
	// Specifies the height, in points, of the thumbnail(s).
	ThumbnailHeight int32 `json:"ThumbnailHeight,omitempty"`
}
