/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FontStyle Defines the different available font styles.
type FontStyle string

// List of FontStyle
const (
	REGULAR FontStyle = "Regular"
	BOLD FontStyle = "Bold"
	ITALIC FontStyle = "Italic"
	BOLD_ITALIC FontStyle = "BoldItalic"
)
