/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfRemoveTextParameters Represents the parameters for a remove text action.
type PdfRemoveTextParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the page or the page range whose text shall be removed.
	PageRange string `json:"PageRange"`
	// Specifies whether only hidden text shall be removed.
	RemoveOnlyHiddenText bool `json:"RemoveOnlyHiddenText,omitempty"`
}
