/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MicrSymbolInfo Holds detailed information about a magnetic ink symbol detected by a MICR process.
type MicrSymbolInfo struct {
	// Specifies the best candidate for the character representation of the detected symbol.
	SymbolValue *string `json:"SymbolValue,omitempty"`
	// Specifies the second best candidate for the character representation of the detected symbol.
	SymbolValue2 *string `json:"SymbolValue2,omitempty"`
	// Specifies the top coordinate of the symbol, in pixels.
	Top int32 `json:"Top,omitempty"`
	// Specifies the left coordinate of the symbol, in pixels.
	Left int32 `json:"Left,omitempty"`
	// Specifies the bottom coordinate of the symbol, in pixels.
	Bottom int32 `json:"Bottom,omitempty"`
	// Specifies the right coordinate of the symbol, in pixels.
	Right int32 `json:"Right,omitempty"`
	// Specifies the number of the line on which the symbol has been detected.
	Line int32 `json:"Line,omitempty"`
	// Specifies the level of confidence of the best detected symbol candidate.
	Confidence float32 `json:"Confidence,omitempty"`
	// Specifies the level of confidence of the second best detected symbol candidate.
	Confidence2 float32 `json:"Confidence2,omitempty"`
}
