/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ContentHorizontalPosition Defines the different horizontal positions for content added on a page.
type ContentHorizontalPosition string

// List of ContentHorizontalPosition
const (
	CENTER ContentHorizontalPosition = "Center"
	LEFT ContentHorizontalPosition = "Left"
	RIGHT ContentHorizontalPosition = "Right"
	ABSOLUTE ContentHorizontalPosition = "Absolute"
)
