/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfInitViewPageMode Defines how the document shall be displayed when opened.
type PdfInitViewPageMode string

// List of PdfInitViewPageMode
const (
	NONE PdfInitViewPageMode = "None"
	OUTLINE PdfInitViewPageMode = "Outline"
	THUMBNAILS PdfInitViewPageMode = "Thumbnails"
	FULL_SCREEN PdfInitViewPageMode = "FullScreen"
	OC PdfInitViewPageMode = "OC"
	ATTACHMENTS PdfInitViewPageMode = "Attachments"
)
