/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// EncryptionAlgorithm Specifies the encryption algorithm.
type EncryptionAlgorithm string

// List of EncryptionAlgorithm
const (
	PDF_ENCRYPTION_NONE EncryptionAlgorithm = "PdfEncryptionNone"
	PDF_ENCRYPTION40_BIT_RC4 EncryptionAlgorithm = "PdfEncryption40BitRC4"
	PDF_ENCRYPTION128_BIT_RC4 EncryptionAlgorithm = "PdfEncryption128BitRC4"
	PDF_ENCRYPTION128_BIT_AES EncryptionAlgorithm = "PdfEncryption128BitAES"
	PDF_ENCRYPTION256_BIT_AES EncryptionAlgorithm = "PdfEncryption256BitAES"
)
