/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SignatureCertificationLevel Specifies the level of the signature certification.
type SignatureCertificationLevel string

// List of SignatureCertificationLevel
const (
	NOT_CERTIFIED SignatureCertificationLevel = "NotCertified"
	NO_CHANGES SignatureCertificationLevel = "NoChanges"
	FORM_FILLING SignatureCertificationLevel = "FormFilling"
	FORM_FILLING_AND_ANNOTATIONS SignatureCertificationLevel = "FormFillingAndAnnotations"
)
