/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfExtractTextParameters Represents the parameters for an extract text action.
type PdfExtractTextParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to extract text from.
	PageRange string `json:"PageRange"`
	TextExtractionMode PdfExtractTextMode `json:"TextExtractionMode,omitempty"`
	// Specifies the left coordinate of the text extraction area for the PageAreaFormated extract mode.
	TextExtractionAreaLeft float32 `json:"TextExtractionAreaLeft,omitempty"`
	// Specifies the top coordinate of the text extraction area for the PageAreaFormated extract mode.
	TextExtractionAreaTop float32 `json:"TextExtractionAreaTop,omitempty"`
	// Specifies the width of the text extraction area for the PageAreaFormated extract mode.
	TextExtractionAreaWidth float32 `json:"TextExtractionAreaWidth,omitempty"`
	// Specifies the height of the text extraction area for the PageAreaFormated extract mode.
	TextExtractionAreaHeight float32 `json:"TextExtractionAreaHeight,omitempty"`
	// Specifies whether the CSV output should include header information.
	IncludeHeader bool `json:"IncludeHeader,omitempty"`
}
