/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SignatureHash Specifies the SHA (hash) algorithm to use while signing.
type SignatureHash string

// List of SignatureHash
const (
	SHA1 SignatureHash = "SHA1"
	SHA256 SignatureHash = "SHA256"
	SHA512 SignatureHash = "SHA512"
	SHA224 SignatureHash = "SHA224"
	SHA384 SignatureHash = "SHA384"
)
