/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ContentVerticalPosition Defines the different possible vertical positions for content added on a page.
type ContentVerticalPosition string

// List of ContentVerticalPosition
const (
	CENTER ContentVerticalPosition = "Center"
	TOP ContentVerticalPosition = "Top"
	BOTTOM ContentVerticalPosition = "Bottom"
	ABSOLUTE ContentVerticalPosition = "Absolute"
)
