/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PageOrientationInfo Represents information about the orientation of a given page.
type PageOrientationInfo struct {
	// Specifies the number of the page.
	PageNumber int32 `json:"PageNumber,omitempty"`
	// Specifies, clockwise in degrees, the rotation angle of the page.
	RotationAngle int32 `json:"RotationAngle,omitempty"`
}
