/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PrintQuality Specifies the quality level to be used to print documents.
type PrintQuality string

// List of PrintQuality
const (
	LOW PrintQuality = "Low"
	MEDIUM PrintQuality = "Medium"
	HIGH PrintQuality = "High"
	VERY_HIGH PrintQuality = "VeryHigh"
)
