/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfMergePagesParameters Represents the parameters for a merge pages action request.
type PdfMergePagesParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the range of pages to be combined.
	PageRange string `json:"PageRange"`
	// Specifies whether the merged pages shall be removed from the document.
	RemovePages bool `json:"RemovePages,omitempty"`
}
