/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RubberStampAnnotationParameters Represents information about the Rubber Stamp Annotation.
type RubberStampAnnotationParameters struct {
	AnnotationLayout DrawableContentLayoutParameters `json:"AnnotationLayout"`
	RubberStampIcon RubberStampAnnotationIcon `json:"RubberStampIcon,omitempty"`
	// Specifies the title of the annotation, if any.
	Title *string `json:"Title,omitempty"`
	// Specify the content of the annotation, if any.
	Content *string `json:"Content,omitempty"`
	// Specifies the color of the annotation, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").
	Color *string `json:"Color,omitempty"`
}
