/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ContentEncoding Indicates the encoding mode of data.
type ContentEncoding string

// List of ContentEncoding
const (
	IDENTITY ContentEncoding = "Identity"
	GZIP ContentEncoding = "Gzip"
)
