/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfAnnotateParameters Represents the parameters for an annotate action.
type PdfAnnotateParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the page or the range of page to be annotated.
	PageRange string `json:"PageRange"`
	AnnotationType AnnotationType `json:"AnnotationType,omitempty"`
	StickyNoteAnnotationParameters StickyNoteAnnotationParameters `json:"StickyNoteAnnotationParameters,omitempty"`
	LinkAnnotationParameters LinkAnnotationParameters `json:"LinkAnnotationParameters,omitempty"`
	FreeTextAnnotationParameters FreeTextAnnotationParameters `json:"FreeTextAnnotationParameters,omitempty"`
	LineAnnotationParameters LineAnnotationParameters `json:"LineAnnotationParameters,omitempty"`
	SquareAndCircleAnnotationParameters SquareAndCircleAnnotationParameters `json:"SquareAndCircleAnnotationParameters,omitempty"`
	RubberStampAnnotationParameters RubberStampAnnotationParameters `json:"RubberStampAnnotationParameters,omitempty"`
}
