/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfDrawImageParameters Represents the parameters for a draw image action.
type PdfDrawImageParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the page or the page range on which the image shall be drawn.
	PageRange string `json:"PageRange"`
	// Specifies the data of the image to be drawn.
	ImageData *string `json:"ImageData,omitempty"`
	// Specifies the file ID of the image to be drawn.
	ImageFileId *string `json:"ImageFileId,omitempty"`
	// Specifies the level of quality to be used for the compression, from 1 (poorest) to 100 (greatest).
	Quality int32 `json:"Quality,omitempty"`
	ColorImageCompression PdfImageCompressionScheme `json:"ColorImageCompression,omitempty"`
	BitonalCompression PdfImageCompressionScheme `json:"BitonalCompression,omitempty"`
	ImageLayout DrawableContentLayoutParameters `json:"ImageLayout,omitempty"`
}
