/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfSplitResponse Represents the response to a split action request.
type PdfSplitResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Specifies the identifier(s) of the file(s) created as a result of the action.
	FileIds *[]string `json:"FileIds,omitempty"`
	// Specifies the data of the file(s) created as a result of the action.
	FileData *[]string `json:"FileData,omitempty"`
}
