/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageRotateParameters Represents the parameters for an image rotate action.
type ImageRotateParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to rotate.
	PageRange string `json:"PageRange"`
	// Specifies the rotation angle, clockwise in degrees, which can be either positive and negative and any multiple of 90.
	RotationAngle float32 `json:"RotationAngle"`
	// Specifies whether the page(s) shall be flipped horizontally.
	FlipHorizontally bool `json:"FlipHorizontally,omitempty"`
	// Specifies whether the page(s) shall be flipped vertically.
	FlipVertically bool `json:"FlipVertically,omitempty"`
}
