/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfTextParameters Represents the basic parameters for text content.
type PdfTextParameters struct {
	// Specifies the text.
	Text *string `json:"Text,omitempty"`
	// Specifies the color of the text, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").
	TextColor *string `json:"TextColor,omitempty"`
	// Specifies the name of the font to be used.
	FontName *string `json:"FontName,omitempty"`
	StandardFontName StandardFontName `json:"StandardFontName,omitempty"`
	FontStyle FontStyle `json:"FontStyle,omitempty"`
	// Specifies the size of the font.
	FontSize int32 `json:"FontSize,omitempty"`
}
