/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfFlattenParameters Represents the parameters for a flatten action.
type PdfFlattenParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies whether the annotations shall be flattened.
	FlattenAnnotations bool `json:"FlattenAnnotations,omitempty"`
	// Specifies whether the form-fields shall be flattened.
	FlattenFormFields bool `json:"FlattenFormFields,omitempty"`
	// Specifies whether the layers shall be flattened.
	FlattenLayers bool `json:"FlattenLayers,omitempty"`
	// Specifies the range of page whose form-fields and annotations shall be flattened, if any.
	PageRange *string `json:"PageRange,omitempty"`
}
