/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DocuViewareSaveResponse Represents the response to a save as JPEG action request.
type DocuViewareSaveResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Specifies the data of the produced file.
	Content *string `json:"Content,omitempty"`
	// Specifies content type of the produced data.
	ContentType *string `json:"ContentType,omitempty"`
}
