/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SquareAndCircleAnnotationParameters Represents information about the Square / Circle Annotation.
type SquareAndCircleAnnotationParameters struct {
	AnnotationLayout DrawableContentLayoutParameters `json:"AnnotationLayout"`
	// Specifies the title of the annotation, if any.
	Title *string `json:"Title,omitempty"`
	// Specify the content of the annotation, if any.
	Content *string `json:"Content,omitempty"`
	LineWidth ContentSize `json:"LineWidth,omitempty"`
	// Specifies the absolute thickness of the annotation, in points.
	AbsoluteAnnotationLineWidth float32 `json:"AbsoluteAnnotationLineWidth,omitempty"`
	// Specifies the color of the annotation, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").
	Color *string `json:"Color,omitempty"`
}
