/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfMovePageParameters Represents the parameters for a move pages action.
type PdfMovePageParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to be moved.
	SourcePageRange string `json:"SourcePageRange"`
	// Specifies the number of the destination page.
	DestinationPage int32 `json:"DestinationPage"`
}
