/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Font Represents a font.
type Font struct {
	FontStyle FontStyle `json:"FontStyle,omitempty"`
	// Specifies the family name of the font, i.e: \"Arial\".
	FamilyName *string `json:"FamilyName,omitempty"`
}
