/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageReadBarcodesParameters Represents the parameters for a read barcode action.
type ImageReadBarcodesParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to read the barcodes from.
	PageRange string `json:"PageRange"`
	// Specifies the left coordinate, in pixel, of the region to process.
	RoiLeft int32 `json:"RoiLeft,omitempty"`
	// Specifies the top coordinate, in pixel, of the region to process.
	RoiTop int32 `json:"RoiTop,omitempty"`
	// Specifies the width, in pixel, of the region to process. 0 causes the entire image to be processed.
	RoiWidth int32 `json:"RoiWidth,omitempty"`
	// Specifies the height, in pixel, of the region to process. 0 causes the entire image to be processed.
	RoiHeight int32 `json:"RoiHeight,omitempty"`
	ScanMode ScanMode `json:"ScanMode,omitempty"`
	// Specifies whether the barcodes of type 1D shall be read.
	ScanBarcode1D bool `json:"ScanBarcode1D,omitempty"`
	// Specifies whether the barcodes of type QR shall be read.
	ScanBarcodeQR bool `json:"ScanBarcodeQR,omitempty"`
	// Specifies whether the barcodes of type Micro QR shall be read.
	ScanBarcodeMicroQR bool `json:"ScanBarcodeMicroQR,omitempty"`
	// Specifies whether the barcodes of type PDF 147 shall be read.
	ScanBarcodePDF417 bool `json:"ScanBarcodePDF417,omitempty"`
	// Specifies whether the barcodes of type Data Matrix shall be read.
	ScanBarcodeDataMatrix bool `json:"ScanBarcodeDataMatrix,omitempty"`
	// Specifies whether the barcodes of type Aztec shall be read.
	ScanBarcodeAztec bool `json:"ScanBarcodeAztec,omitempty"`
}
