/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageAdjustParameters Represents the parameters for an image adjustment action.
type ImageAdjustParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to adjust.
	PageRange string `json:"PageRange"`
	// Specifies the left coordinate, in pixel, of the region to process.
	RoiLeft int32 `json:"RoiLeft,omitempty"`
	// Specifies the top coordinate, in pixel, of the region to process.
	RoiTop int32 `json:"RoiTop,omitempty"`
	// Specifies the width, in pixel, of the region to process. 0 causes the entire image to be processed.
	RoiWidth int32 `json:"RoiWidth,omitempty"`
	// Specifies the height, in pixel, of the region to process. 0 causes the entire image to be processed.
	RoiHeight int32 `json:"RoiHeight,omitempty"`
	// Specifies the gamma correction parameter.
	GammaCorrection int32 `json:"GammaCorrection,omitempty"`
	// Specifies the brightness parameter.
	Brightness int32 `json:"Brightness,omitempty"`
	// Specifies the contrast parameter.
	Contrast int32 `json:"Contrast,omitempty"`
	// Specifies the saturation parameter.
	Saturation int32 `json:"Saturation,omitempty"`
	// Specifies whether the contrast shall be automatically enhanced.
	AutoContrastEnhancement bool `json:"AutoContrastEnhancement,omitempty"`
	// Specifies whether a contrast histogram stretch filter shall be performed.
	ContrastHistogramStretch bool `json:"ContrastHistogramStretch,omitempty"`
}
