/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfExtractTextMode Defines the different available modes for text extraction.
type PdfExtractTextMode string

// List of PdfExtractTextMode
const (
	WHOLE_PAGE_READABLE PdfExtractTextMode = "WholePageReadable"
	PAGE_AREA_READABLE PdfExtractTextMode = "PageAreaReadable"
	WHOLE_PAGE_CSV PdfExtractTextMode = "WholePageCSV"
)
