/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DocumentGetPreviewResponse Represents the response to a get document preview action request.
type DocumentGetPreviewResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Specifies the page count of the document.
	PageCount int32 `json:"PageCount,omitempty"`
	// Specifies the data of a thumbnail from the first page of the document, in PNG format.
	ThumbnailData *string `json:"ThumbnailData,omitempty"`
	DocumentFormat DocumentFormat `json:"DocumentFormat,omitempty"`
}
