/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageCropParameters Represents the parameters for an image crop action.
type ImageCropParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to crop.
	PageRange string `json:"PageRange"`
	// Specifies the crop box left coordinate.
	CropBoxLeft int32 `json:"CropBoxLeft"`
	// Specifies the crop box top coordinate.
	CropBoxTop int32 `json:"CropBoxTop"`
	// Specifies the crop box width.
	CropBoxWidth int32 `json:"CropBoxWidth"`
	// Specifies the crop box height.
	CropBoxHeight int32 `json:"CropBoxHeight"`
	CropUnit CropUnit `json:"CropUnit,omitempty"`
}
