/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SignatureMode Specifies the security handler of a signature.
type SignatureMode string

// List of SignatureMode
const (
	ADOBE_PPKMS SignatureMode = "AdobePPKMS"
	ADOBE_PPK_LITE SignatureMode = "AdobePPKLite"
	ADOBE_CADES SignatureMode = "AdobeCADES"
)
