/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfSetPasswordParameters Represents the parameters for an unprotect action.
type PdfSetPasswordParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the password to be used to open the PDF. It can be the user or the owner password.
	Password string `json:"Password"`
}
