/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfOcrParameters Represents the parameters for an OCR action.
type PdfOcrParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the page or the page range to be processed.
	PageRange string `json:"PageRange"`
	// Specifies the language to be used for the OCR.
	Language *string `json:"Language,omitempty"`
	// Specifies if pages containing text must be ignored (in such case no token is charged).
	SkipPageWithText bool `json:"SkipPageWithText,omitempty"`
}
