/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfSaveAsTiffParameters Represents the parameters for a save as TIFF action.
type PdfSaveAsTiffParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to be saved as TIFF.
	PageRange *string `json:"PageRange,omitempty"`
	Compression TiffSaveCompression `json:"Compression,omitempty"`
	// Specifies the level of quality to be used if JPEG compression is used, from 1 (poorest) to 100 (greatest).
	JpegQuality int32 `json:"JpegQuality,omitempty"`
	// Specifies whether the TIFF shall be saved in CMYK color space or not.
	UseCMYK bool `json:"UseCMYK,omitempty"`
	// Specifies the resolution to be used for the rendition process.
	Resolution float32 `json:"Resolution,omitempty"`
	// Specifies whether the form fields of the PDF shall be rendered.
	RenderFormFields bool `json:"RenderFormFields,omitempty"`
	// Specifies whether the initial image resolution must be kept in case of raster-pdf processing.
	KeepRasterPDFResolution bool `json:"KeepRasterPDFResolution,omitempty"`
}
