/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PageImage Holds the data of an image from a given page of a document.
type PageImage struct {
	// Specifies the number of the page.
	PageNumber int32 `json:"PageNumber,omitempty"`
	// The data of the image.
	ImageData *string `json:"ImageData,omitempty"`
	// Specifies the name of the file.
	FileName *string `json:"FileName,omitempty"`
}
