/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfSaveAsPngParameters Represents the parameters for a save as PNG acion.
type PdfSaveAsPngParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to be saved as PNG.
	PageRange *string `json:"PageRange,omitempty"`
	// Specifies the level of compression to be used for the PNG output, between 0 (no compression - faster encoding) to 9(max compression - slower encoding).
	Compression int32 `json:"Compression,omitempty"`
	// Specifies if the produced PNG image must be interlaced.
	Interlaced bool `json:"Interlaced,omitempty"`
	// Specifies the resolution to be used for the rendition process.
	Resolution float32 `json:"Resolution,omitempty"`
	// Specifies whether the form fields of the PDF shall be rendered.
	RenderFormFields bool `json:"RenderFormFields,omitempty"`
	// Specifies if the initial image resolution must be kept in case of raster-pdf processing.
	KeepRasterPDFResolution bool `json:"KeepRasterPDFResolution,omitempty"`
}
