/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfClearPageParameters Represents the parameters for a clear page action.
type PdfClearPageParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the page or the range of pages to be cleared.
	PageRange string `json:"PageRange"`
}
