/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageQuality Specifies the quality to be used for the compression of the images of the docuent.
type ImageQuality string

// List of ImageQuality
const (
	IMAGE_QUALITY_LOW ImageQuality = "ImageQualityLow"
	IMAGE_QUALITY_MEDIUM ImageQuality = "ImageQualityMedium"
	IMAGE_QUALITY_HIGH ImageQuality = "ImageQualityHigh"
	IMAGE_QUALITY_VERY_HIGH ImageQuality = "ImageQualityVeryHigh"
)
