/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DocumentAlignment the model 'DocumentAlignment'
type DocumentAlignment string

// List of DocumentAlignment
const (
	MIDDLE_LEFT DocumentAlignment = "MiddleLeft"
	MIDDLE_RIGHT DocumentAlignment = "MiddleRight"
	MIDDLE_CENTER DocumentAlignment = "MiddleCenter"
	TOP_LEFT DocumentAlignment = "TopLeft"
	TOP_RIGHT DocumentAlignment = "TopRight"
	TOP_CENTER DocumentAlignment = "TopCenter"
	BOTTOM_LEFT DocumentAlignment = "BottomLeft"
	BOTTOM_RIGHT DocumentAlignment = "BottomRight"
	BOTTOM_CENTER DocumentAlignment = "BottomCenter"
)
