/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageAutoCropParameters Represents the parameters for an image auto cropping action.
type ImageAutoCropParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to crop.
	PageRange string `json:"PageRange"`
	// Specifies the confidence threshold in percentage.
	Confidence float32 `json:"Confidence,omitempty"`
}
