/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageSaveAsPngResponse Represents the response to a save as PNG action request.
type ImageSaveAsPngResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// The image(s) saved as PNG.
	PageImages *[]PageImage `json:"PageImages,omitempty"`
}
