/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfConformance Specifies PDF versions and conformance levels of a PDF document.
type PdfConformance string

// List of PdfConformance
const (
	UNKNOWN PdfConformance = "Unknown"
	PDF10 PdfConformance = "PDF10"
	PDF11 PdfConformance = "PDF11"
	PDF12 PdfConformance = "PDF12"
	PDF13 PdfConformance = "PDF13"
	PDF14 PdfConformance = "PDF14"
	PDF15 PdfConformance = "PDF15"
	PDF16 PdfConformance = "PDF16"
	PDF17 PdfConformance = "PDF17"
	PDF20 PdfConformance = "PDF20"
	PDFA1A PdfConformance = "PDFA1a"
	PDFA1B PdfConformance = "PDFA1b"
	PDFA2A PdfConformance = "PDFA2a"
	PDFA2U PdfConformance = "PDFA2u"
	PDFA2B PdfConformance = "PDFA2b"
	PDFA3A PdfConformance = "PDFA3a"
	PDFA3U PdfConformance = "PDFA3u"
	PDFA3B PdfConformance = "PDFA3b"
	PDFUA1 PdfConformance = "PDFUA1"
)
