/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageSaveAsPdfParameters Represents the parameters for a save as PDF action.
type ImageSaveAsPdfParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to be saved as PDF.
	PageRange *string `json:"PageRange,omitempty"`
	Conformance PdfConformance `json:"Conformance,omitempty"`
	ColorImageCompression PdfImageCompressionScheme `json:"ColorImageCompression,omitempty"`
	BitonalImageCompression PdfImageCompressionScheme `json:"BitonalImageCompression,omitempty"`
	// Specifies is color detection must be used.
	EnableColorDetection bool `json:"EnableColorDetection,omitempty"`
	// Specifies the quality to be used for the compression of the images from the PDF.  Must be in the range [0 (best compression - worst quality) - 100 (worst quality - best compression)].
	ImageQuality int32 `json:"ImageQuality,omitempty"`
	// Specifies the resolution for downscaling images, if any.
	DownscaleResolution int32 `json:"DownscaleResolution,omitempty"`
	// Specifies whether the PDF shall be optimized for online distribution.
	FastWebView bool `json:"FastWebView,omitempty"`
}
