/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ReduceErrorInfo Represents information about an error which caused the failure of a reduce action.
type ReduceErrorInfo struct {
	ErrorCode ReduceErrorCode `json:"ErrorCode,omitempty"`
	// The number of the page processed when the error occured.
	PageNumber int32 `json:"PageNumber,omitempty"`
	// The error message associated with the error, if any.
	ExtErrorMessage *string `json:"ExtErrorMessage,omitempty"`
}
