/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RotateFlip the model 'RotateFlip'
type RotateFlip string

// List of RotateFlip
const (
	ROTATE_NONE_FLIP_NONE RotateFlip = "RotateNoneFlipNone"
	ROTATE90_FLIP_NONE RotateFlip = "Rotate90FlipNone"
	ROTATE180_FLIP_NONE RotateFlip = "Rotate180FlipNone"
	ROTATE270_FLIP_NONE RotateFlip = "Rotate270FlipNone"
	ROTATE_NONE_FLIP_X RotateFlip = "RotateNoneFlipX"
	ROTATE90_FLIP_X RotateFlip = "Rotate90FlipX"
	ROTATE180_FLIP_X RotateFlip = "Rotate180FlipX"
	ROTATE270_FLIP_X RotateFlip = "Rotate270FlipX"
)
