/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ViewerZoomMode the model 'ViewerZoomMode'
type ViewerZoomMode string

// List of ViewerZoomMode
const (
	ZOOM_MODE100 ViewerZoomMode = "ZoomMode100"
	ZOOM_MODE_FIT_TO_VIEWER ViewerZoomMode = "ZoomModeFitToViewer"
	ZOOM_MODE_WIDTH_VIEWER ViewerZoomMode = "ZoomModeWidthViewer"
	ZOOM_MODE_CUSTOM ViewerZoomMode = "ZoomModeCustom"
	ZOOM_MODE_HEIGHT_VIEWER ViewerZoomMode = "ZoomModeHeightViewer"
	ZOOM_MODE_TO_VIEWER ViewerZoomMode = "ZoomModeToViewer"
	ZOOM_MODE_SHRINK_TO_VIEWER_WIDTH ViewerZoomMode = "ZoomModeShrinkToViewerWidth"
)
