/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ScanMode Defines the different available scan modes.
type ScanMode string

// List of ScanMode
const (
	FAVOR_SPEED ScanMode = "FavorSpeed"
	FAVOR_ACCURACY ScanMode = "FavorAccuracy"
)
