/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageConvertColorDepthParameters Represents the parameters for an image color depth change action.
type ImageConvertColorDepthParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of pages to process.
	PageRange string `json:"PageRange"`
	ConvertColorDepthMode ColorDepthConversionMethod `json:"ConvertColorDepthMode"`
	// Specifies the threshold for a conversion using the Depth1BppOtsu method.
	Depth1BppOtsuThreshold int32 `json:"Depth1BppOtsuThreshold,omitempty"`
	// Specifies the threshold for a conversion using the Depth1BppBradley method.
	Depth1BppBradleyThreshold int32 `json:"Depth1BppBradleyThreshold,omitempty"`
	// Specifies the factor for a conversion using the Depth1BppSauvola method.
	Depth1BppSauvolaFactor float32 `json:"Depth1BppSauvolaFactor,omitempty"`
}
