/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DocumentFormat Specifies the format of a document.
type DocumentFormat string

// List of DocumentFormat
const (
	UNKNOWN DocumentFormat = "UNKNOWN"
	ICO DocumentFormat = "ICO"
	BMP DocumentFormat = "BMP"
	WBMP DocumentFormat = "WBMP"
	JPEG DocumentFormat = "JPEG"
	GIF DocumentFormat = "GIF"
	PNG DocumentFormat = "PNG"
	TIFF DocumentFormat = "TIFF"
	FAXG3 DocumentFormat = "FAXG3"
	EXIF DocumentFormat = "EXIF"
	EMF DocumentFormat = "EMF"
	WMF DocumentFormat = "WMF"
	JNG DocumentFormat = "JNG"
	KOALA DocumentFormat = "KOALA"
	IFF DocumentFormat = "IFF"
	MNG DocumentFormat = "MNG"
	PCD DocumentFormat = "PCD"
	PCX DocumentFormat = "PCX"
	PBM DocumentFormat = "PBM"
	PBMRAW DocumentFormat = "PBMRAW"
	PFM DocumentFormat = "PFM"
	PGM DocumentFormat = "PGM"
	PGMRAW DocumentFormat = "PGMRAW"
	PPM DocumentFormat = "PPM"
	PPMRAW DocumentFormat = "PPMRAW"
	RAS DocumentFormat = "RAS"
	TARGA DocumentFormat = "TARGA"
	PSD DocumentFormat = "PSD"
	CUT DocumentFormat = "CUT"
	XBM DocumentFormat = "XBM"
	XPM DocumentFormat = "XPM"
	DDS DocumentFormat = "DDS"
	HDR DocumentFormat = "HDR"
	SGI DocumentFormat = "SGI"
	EXR DocumentFormat = "EXR"
	J2_K DocumentFormat = "J2K"
	JP2 DocumentFormat = "JP2"
	PICT DocumentFormat = "PICT"
	RAW DocumentFormat = "RAW"
	WEBP DocumentFormat = "WEBP"
	DICOM DocumentFormat = "DICOM"
	JBIG DocumentFormat = "JBIG"
	JBIG2 DocumentFormat = "JBIG2"
	WSQ DocumentFormat = "WSQ"
	PDF DocumentFormat = "PDF"
	SVG DocumentFormat = "SVG"
	TXT DocumentFormat = "TXT"
	DOCX DocumentFormat = "DOCX"
	RTF DocumentFormat = "RTF"
	DXF DocumentFormat = "DXF"
	ODT DocumentFormat = "ODT"
	XLSX DocumentFormat = "XLSX"
	PPTX DocumentFormat = "PPTX"
)
