/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"os"
)
// InlineObject1 struct for InlineObject1
type InlineObject1 struct {
	// The data of the document.
	FileData *os.File `json:"fileData"`
	LoadImageParameters LoadImageParameters `json:"loadImageParameters,omitempty"`
}
