/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageDetectBlankPagesResponse Represents the response to a detect blank pages action request.
type ImageDetectBlankPagesResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Specifies the number of the pages which have been detected to be blank.
	DetectedBlankPages *[]int32 `json:"DetectedBlankPages,omitempty"`
}
