/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Barcode1DSymbology Defines the different supported linear barcode symbologies.
type Barcode1DSymbology string

// List of Barcode1DSymbology
const (
	NONE Barcode1DSymbology = "None"
	INDUSTRIAL2OF5 Barcode1DSymbology = "Industrial2of5"
	INVERTED2OF5 Barcode1DSymbology = "Inverted2of5"
	INTERLEAVED2OF5 Barcode1DSymbology = "Interleaved2of5"
	IATA2OF5 Barcode1DSymbology = "Iata2of5"
	MATRIX2OF5 Barcode1DSymbology = "Matrix2of5"
	CODE39 Barcode1DSymbology = "Code39"
	CODEABAR Barcode1DSymbology = "Codeabar"
	BCD_MATRIX Barcode1DSymbology = "BcdMatrix"
	DATA_LOGIC2OF5 Barcode1DSymbology = "DataLogic2of5"
	CODE128 Barcode1DSymbology = "Code128"
	CODE93 Barcode1DSymbology = "CODE93"
	EAN13 Barcode1DSymbology = "EAN13"
	UPCA Barcode1DSymbology = "UPCA"
	EAN8 Barcode1DSymbology = "EAN8"
	UPCE Barcode1DSymbology = "UPCE"
	ADD5 Barcode1DSymbology = "ADD5"
	ADD2 Barcode1DSymbology = "ADD2"
)
