/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MicrFont Specifies the two major MICR fonts in use.
type MicrFont string

// List of MicrFont
const (
	CMC7 MicrFont = "CMC7"
	E13_B MicrFont = "E13B"
)
