/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageMicrParameters Represents the parameters for a MICR action.
type ImageMicrParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the page or the range of page to be processed.
	PageRange string `json:"PageRange"`
	Font MicrFont `json:"Font"`
	Context MicrContext `json:"Context"`
	// Specifies the characters to be ignored by the recognition process.
	WhiteList *string `json:"WhiteList,omitempty"`
	// Specifies the left coordinate, in pixel, of the region to process.
	RoiLeft int32 `json:"RoiLeft,omitempty"`
	// Specifies the top coordinate, in pixel, of the region to process.
	RoiTop int32 `json:"RoiTop,omitempty"`
	// Specifies the width, in pixel, of the region to process. 0 causes the entire image to be processed.
	RoiWidth int32 `json:"RoiWidth,omitempty"`
	// Specifies the height, in pixel, of the region to process. 0 causes the entire image to be processed.
	RoiHeight int32 `json:"RoiHeight,omitempty"`
	// Specifies the number of symbols expected to be detected, use 0 if unknown.
	ExpectedSymbolsCount int32 `json:"ExpectedSymbolsCount,omitempty"`
}
