/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AnnotationType Defines the different available types of annotations.
type AnnotationType string

// List of AnnotationType
const (
	STICKY_NOTE AnnotationType = "StickyNote"
	LINK AnnotationType = "Link"
	FREE_TEXT AnnotationType = "FreeText"
	LINE AnnotationType = "Line"
	SQUARE AnnotationType = "Square"
	CIRCLE AnnotationType = "Circle"
	RUBBER_STAMP AnnotationType = "RubberStamp"
)
