/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfGetInfoResponse Represents the response to a get info action request.
type PdfGetInfoResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Specifies the number of pages of the PDF.
	PageCount int32 `json:"PageCount,omitempty"`
	// Specifies the version of the PDF.
	Version *string `json:"Version,omitempty"`
	// Specifies the author name specified within the PDF, if any.
	Author *string `json:"Author,omitempty"`
	// Specifies the document title specified within the PDF, if any.
	Title *string `json:"Title,omitempty"`
	// Specifies the document subject specified within the PDF, if any.
	Subject *string `json:"Subject,omitempty"`
	// Specifies the producer name specified within the PDF, if any.
	Producer *string `json:"Producer,omitempty"`
	// Specifies the metadata contained within the PDF, if any.
	Metadata *string `json:"Metadata,omitempty"`
	// Specifies the keywords associated with the PDF, if any.
	Keywords *string `json:"Keywords,omitempty"`
	// Specifies if the PDF is protected with a user password.
	HasUserPassword bool `json:"HasUserPassword,omitempty"`
	// Specifies if the PDF is protected with a owner password.
	HasOwnerPassword bool `json:"HasOwnerPassword,omitempty"`
	Encryption EncryptionAlgorithm `json:"Encryption,omitempty"`
	// Specifies if the user is allowed to print the document, but possibly not at the highest quality level.
	CanPrint bool `json:"CanPrint,omitempty"`
	// Specifies if the user is allowed to copy or extract text and graphics from the document.
	CanCopy bool `json:"CanCopy,omitempty"`
	// Specifies if the user is allowed to modify the document.
	CanModify bool `json:"CanModify,omitempty"`
	// Specifies if the user is allowed to add annotations.
	CanAddNotes bool `json:"CanAddNotes,omitempty"`
	// Specifies if the user is allowed to fill-in form fields.
	CanFillFields bool `json:"CanFillFields,omitempty"`
	// Specifies if the user is allowed for copying or extracting for use with accessibility features.
	CanCopyAccess bool `json:"CanCopyAccess,omitempty"`
	// Specifies if the user is allowed to assemble the document.
	CanAssemble bool `json:"CanAssemble,omitempty"`
	// Specifies if the user is allowed to print the document with high resolution.
	CanPrintFull bool `json:"CanPrintFull,omitempty"`
}
