/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageGetPageThumbnailResponse Represents the response to a get page thumbnail action request.
type ImageGetPageThumbnailResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Contains all the obtained thumbnails.
	PageThumbnails *[]PageImage `json:"PageThumbnails,omitempty"`
}
