/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ResizeUnit Specifies the unit of measure for the given data.
type ResizeUnit string

// List of ResizeUnit
const (
	PIXEL ResizeUnit = "Pixel"
	PERCENT ResizeUnit = "Percent"
)
