/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfProtectParameters Represents the parameters for a protect action.
type PdfProtectParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the owner password to be set.
	OwnerPassword *string `json:"OwnerPassword,omitempty"`
	// Specifies the user password to be set.
	UserPassword *string `json:"UserPassword,omitempty"`
	Encryption EncryptionAlgorithm `json:"Encryption,omitempty"`
	// Allows the user to print the document, but possibly not at the highest quality level. Ignored if no encryption algorithm is set.
	CanPrint bool `json:"CanPrint,omitempty"`
	// Allows the user to copy or extract text and graphics from the document. Ignored if the no encryption scheme is set.
	CanCopy bool `json:"CanCopy,omitempty"`
	// Allows the user to modify the document. Ignored if the no encryption scheme is set.
	CanModify bool `json:"CanModify,omitempty"`
	// Allows the user to add annotations. Ignored if the no encryption scheme is set.
	CanAddNotes bool `json:"CanAddNotes,omitempty"`
	// Allows the user to fill-in form fields. Only works with 128-bit encryption.
	CanFillFields bool `json:"CanFillFields,omitempty"`
	// Enables copying or extracting for use with accessibility features. Only works with 128-bit encryption.
	CanCopyAccess bool `json:"CanCopyAccess,omitempty"`
	// Allows the user to assemble the document. Only works with 128-bit encryption.
	CanAssemble bool `json:"CanAssemble,omitempty"`
	// Allows high resolution printing of the document. Only works with 128-bit encryption.
	CanPrintFull bool `json:"CanPrintFull,omitempty"`
}
