/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OutputIntent Defines the intent (color detection) of the image.
type OutputIntent string

// List of OutputIntent
const (
	UNKNOWN OutputIntent = "Unknown"
	BLACK_WHITE OutputIntent = "BlackWhite"
	GRAYSCALE OutputIntent = "Grayscale"
	PALLETIZED OutputIntent = "Palletized"
	COLOR OutputIntent = "Color"
	WHITE OutputIntent = "White"
)
