/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfInsertPageNumberParameters Represents the parameters for an insert page number action.
type PdfInsertPageNumberParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the page or the range of pages on which the page number shall be inserted.
	PageRange string `json:"PageRange"`
	Format PageNumberFormat `json:"Format,omitempty"`
	Layout DrawableContentLayoutParameters `json:"Layout,omitempty"`
	TextParameters PdfAlignedTextParameters `json:"TextParameters,omitempty"`
}
