/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// StandardFontName Defines the different available standard fonts (Standard Type 1) which can be used without prior definition.
type StandardFontName string

// List of StandardFontName
const (
	COURIER StandardFontName = "Courier"
	HELVETICA StandardFontName = "Helvetica"
	TIMES StandardFontName = "Times"
	SYMBOL StandardFontName = "Symbol"
	ZAPF_DINGBATS StandardFontName = "ZapfDingbats"
)
