/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfInitViewLayoutMode Specifies the page layout to be used when the document is opened.
type PdfInitViewLayoutMode string

// List of PdfInitViewLayoutMode
const (
	SINGLE_PAGE PdfInitViewLayoutMode = "SinglePage"
	ONE_COLUMN PdfInitViewLayoutMode = "OneColumn"
	TWO_COLUMN_LEFT PdfInitViewLayoutMode = "TwoColumnLeft"
	TWO_COLUMN_RIGHT PdfInitViewLayoutMode = "TwoColumnRight"
	TWO_PAGE_LEFT PdfInitViewLayoutMode = "TwoPageLeft"
	TWO_PAGE_RIGHT PdfInitViewLayoutMode = "TwoPageRight"
)
