/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageSaveAsTiffMultipageResponse Represents the response to a save as TIFF multipage action request.
type ImageSaveAsTiffMultipageResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Specifies the data of the produced multipage TIFF.
	ImageData *string `json:"ImageData,omitempty"`
	// Specifies the name of the saved document.
	FileName *string `json:"FileName,omitempty"`
}
