/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MicrContext Specifies the MICR context, i.e. the layout type of the data to be recognized.  .
type MicrContext string

// List of MicrContext
const (
	WHOLE_DOCUMENT MicrContext = "WholeDocument"
	LINE_FINDING MicrContext = "LineFinding"
)
