/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DocuViewareSaveParameters Represents the parameters for a Save action.
type DocuViewareSaveParameters struct {
	// Specifies the unique identifier used to identify the user session.
	SessionId string `json:"SessionId"`
	// Specifies the identifier associated with the control.
	ControlId string `json:"ControlId"`
	// Specifies the name of the file to create.
	FileName string `json:"FileName"`
	// Specifies the format of the document to save.  Supported values are tiff, pdf, pdf/a, pdf/a1a, pdf/a1b, pdf/a2a, pdf/a2b, pdf/a2u, pdf/a3a, pdf/a3b, pdf/a3u.
	Format string `json:"Format"`
	// Specifies the number of the page, or the range of pages to be saved into the new file.
	PageRange *string `json:"PageRange,omitempty"`
}
