/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageCloneRegionsParameters Represents the parameters for a clone image region action.
type ImageCloneRegionsParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// The regions to be cloned.
	ImageRegions []ImageRegion `json:"ImageRegions"`
}
