/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageSaveAsPdfResponse Represents the response to a save as PDF action request.
type ImageSaveAsPdfResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Specifies the data of the produced PDF.
	PdfData *string `json:"PdfData,omitempty"`
	// Specifies the name of the saved document.
	FileName *string `json:"FileName,omitempty"`
}
