/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FreeTextAnnotationParameters Represents information about the FreeText Annotation.
type FreeTextAnnotationParameters struct {
	AnnotationLayout DrawableContentLayoutParameters `json:"AnnotationLayout"`
	TextParameters PdfTextParameters `json:"TextParameters,omitempty"`
	// Specifies the title of the annotation, if any.
	Title *string `json:"Title,omitempty"`
	// Specify the subject of the annotation, if any.
	Subject *string `json:"Subject,omitempty"`
	// Specifies if the annotation border shall be drawn.
	ShowBorder bool `json:"ShowBorder,omitempty"`
	// Specifies the color of the annotation, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").
	Color *string `json:"Color,omitempty"`
}
