/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageCloneRegionsResponse Represents the response to a close image action request.
type ImageCloneRegionsResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// The images created as a result of the action.
	ClonedImages *[]ClonedImageRegion `json:"ClonedImages,omitempty"`
}
