/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DrawableContentLayoutParameters Represents information about the layout of a content, on the page it is drawn onto.
type DrawableContentLayoutParameters struct {
	HorizontalPosition ContentHorizontalPosition `json:"HorizontalPosition,omitempty"`
	VerticalPosition ContentVerticalPosition `json:"VerticalPosition,omitempty"`
	Size ContentSize `json:"Size,omitempty"`
	// Specifies whether the content shall be slightly indented from the nearest page edges.
	IndentFromEdges bool `json:"IndentFromEdges,omitempty"`
	// Specifies the absolute horizontal position of the top-left edge of the content, in points.
	AbsolutePositionLeft float32 `json:"AbsolutePositionLeft,omitempty"`
	// Specifies the absolute vertical position of the top-left edge of the content, in points.
	AbsolutePositionTop float32 `json:"AbsolutePositionTop,omitempty"`
	// Specifies the absolute width of the content, in points.
	AbsoluteWidth float32 `json:"AbsoluteWidth,omitempty"`
	// Specifies the absolute height of the content, in points.
	AbsoluteHeight float32 `json:"AbsoluteHeight,omitempty"`
}
