/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LineAnnotationParameters Represents information about the Line Annotation.
type LineAnnotationParameters struct {
	// Specifies if the horizontal coordinate of line annotation start point.
	LineStartX float32 `json:"LineStartX,omitempty"`
	// Specifies if the vertical coordinate of line annotation start point.
	LineStartY float32 `json:"LineStartY,omitempty"`
	// Specifies if the horizontal coordinate of line annotation end point.
	LineEndX float32 `json:"LineEndX,omitempty"`
	// Specifies if the vertical coordinate of line annotation end point.
	LineEndY float32 `json:"LineEndY,omitempty"`
	// Specifies the title of the annotation, if any.
	Title *string `json:"Title,omitempty"`
	// Specify the content of the annotation, if any.
	Content *string `json:"Content,omitempty"`
	LineStartStyle LineAnnotationEndingStyle `json:"LineStartStyle,omitempty"`
	LineEndStyle LineAnnotationEndingStyle `json:"LineEndStyle,omitempty"`
	// Specifies if the popup of annotation shall be opened by default.
	ShowContent bool `json:"ShowContent,omitempty"`
	LineWidth ContentSize `json:"LineWidth,omitempty"`
	// Specifies the absolute line width of the annotation, in points.
	AbsoluteAnnotationLineWidth float32 `json:"AbsoluteAnnotationLineWidth,omitempty"`
	// Specifies the color of the annotation, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").
	Color *string `json:"Color,omitempty"`
}
