/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageDetectBlankPagesParameters Represents the parameters for a detect blank pages action.
type ImageDetectBlankPagesParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the number of the page, or the range of page to be processed.
	PageRange string `json:"PageRange"`
	// Specifies whether the detected blank page(s) shall be removed.
	RemoveDetectedBlankPages bool `json:"RemoveDetectedBlankPages,omitempty"`
}
