/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfClonePageParameters Represents the parameters for a ClonePage action.
type PdfClonePageParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the file identifier of the PDF to be cloned.
	SourceFileId string `json:"SourceFileId"`
	// Specifies the number of the page, or the range of pages to be cloned.
	PageRange string `json:"PageRange"`
	// Specifies the number of the page where the cloned page(s) shall be inserted.
	DestinationPage int32 `json:"DestinationPage"`
}
