/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RubberStampAnnotationIcon Defines the different available icons for a rubber stamp annotation.
type RubberStampAnnotationIcon string

// List of RubberStampAnnotationIcon
const (
	APPROVED RubberStampAnnotationIcon = "Approved"
	NOT_APPROVED RubberStampAnnotationIcon = "NotApproved"
	NOT_FOR_PUBLIC_RELEASE RubberStampAnnotationIcon = "NotForPublicRelease"
	CONFIDENTIAL RubberStampAnnotationIcon = "Confidential"
	FINAL RubberStampAnnotationIcon = "Final"
	FOR_COMMENT RubberStampAnnotationIcon = "ForComment"
	DRAFT RubberStampAnnotationIcon = "Draft"
	FOR_PUBLIC_RELEASE RubberStampAnnotationIcon = "ForPublicRelease"
	SB_COMPLETED RubberStampAnnotationIcon = "SBCompleted"
	SB_INFORMATION_ONLY RubberStampAnnotationIcon = "SBInformationOnly"
	SB_VOID RubberStampAnnotationIcon = "SBVoid"
	SB_PRELIMINARY_RESULTS RubberStampAnnotationIcon = "SBPreliminaryResults"
	SB_REJECTED RubberStampAnnotationIcon = "SBRejected"
	SH_ACCEPTED RubberStampAnnotationIcon = "SHAccepted"
	SH_INITIAL_HERE RubberStampAnnotationIcon = "SHInitialHere"
	SH_SIGN_HERE RubberStampAnnotationIcon = "SHSignHere"
	SH_WITNESS RubberStampAnnotationIcon = "SHWitness"
	D_APPROVED RubberStampAnnotationIcon = "DApproved"
	D_CONFIDENTIAL RubberStampAnnotationIcon = "DConfidential"
	D_RECEIVED RubberStampAnnotationIcon = "DReceived"
	D_REVIEWED RubberStampAnnotationIcon = "DReviewed"
)
