/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfUnprotectParameters Represents the parameters for an unprotect action.
type PdfUnprotectParameters struct {
	// The identifier of the previously uploaded file to be processed.
	FileId string `json:"FileId"`
	// Specifies the password to be used to unprotect the PDF.
	Password string `json:"Password"`
}
