/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DocuViewareGetControlParameters Represents the parameters for a GetControl action.
type DocuViewareGetControlParameters struct {
	// Specifies the unique identifier used to identify the user session.
	SessionID string `json:"SessionID"`
	ControlState DocuViewareControlState `json:"ControlState"`
}
