/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PdfExtractTextResponse Represents the response to an extract text action request.
type PdfExtractTextResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// The text extraction results from individual pages.
	ExtractedText *[]PageText `json:"ExtractedText,omitempty"`
}
