/*
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ImageDetectColorResponse Represents the response to an image color detection action request.
type ImageDetectColorResponse struct {
	Error Error `json:"Error,omitempty"`
	// Specifies the number of remaining tokens.
	RemainingTokens int64 `json:"RemainingTokens,omitempty"`
	// Specifies the result of the color detection operation performed on each page.
	ColorDetectionResults *[]ColorDetectionResult `json:"ColorDetectionResults,omitempty"`
}
